version: '3.8'

services:
  airflow-init:
    image: fulakar/airflow:2.9.3-3.11-req
    env_file:
      - ./parser/dags/.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME_AIRFLOW}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command:
      - bash
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin

  airflow-webserver:
    image: fulakar/airflow:2.9.3-3.11-req
    env_file:
      - ./parser/dags/.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME_AIRFLOW}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./parser/dags/:/opt/airflow/dags/
    ports:
      - "8080:8080"
    command: standalone
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    image: fulakar/airflow:2.9.3-3.11-req
    env_file:
      - ./parser/dags/.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME_AIRFLOW}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./parser/dags/:/opt/airflow/dags/
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
