"""Initial migration

Revision ID: e98e95bf701e
Revises: 
Create Date: 2025-04-09 23:52:09.369874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'e98e95bf701e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_embedd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_with_ticker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_with_ticker_embedd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_hour',
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('ticker_describe',
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker_describe')
    op.drop_table('price_hour')
    op.drop_table('news_with_ticker_embedd')
    op.drop_table('news_with_ticker')
    op.drop_table('news_embedd')
    op.drop_table('news')
    # ### end Alembic commands ###
